# Generated by Django 4.2.5 on 2023-10-09 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billsManager', '0004_userprofile_virtual_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
