# Generated by Django 4.2.5 on 2023-10-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsManager', '0006_billpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10),
        ),
    ]
